name: "arrs"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  radarr:
    image: "11notes/radarr:5.27.5"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "radarr.etc:/radarr/etc"
    tmpfs:
      # required for read-only image
      - "/tmp:uid=1000,gid=1000"
    ports:
      - "3000:7878/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  radarr.etc:

networks:
  frontend: