name: "arrs"
services:
  radarr:
    image: "11notes/radarr:5.22.4"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "radarr.etc:/radarr/etc"
    tmpfs:
      # required for read-only image
      - "/tmp:uid=1000,gid=1000"
    ports:
      - "7878:7878/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  radarr.etc:

networks:
  frontend: